version: 0.2

env:
  variables:
    AWS_REGION: "ap-southeast-1"  # Change to your AWS region
    REPOSITORY_URI: "448049800169.dkr.ecr.ap-southeast-1.amazonaws.com/davidnguyen/beanstalk-demo" # Change to your ECR repo URI
    CODEBUILD_SRC_DIR: .

phases:
  pre_build:
    commands:
      - echo "Logging into Amazon ECR..."
      - echo "CodeBuild source directory: $CODEBUILD_SRC_DIR"
      - ls -R $CODEBUILD_SRC_DIR  # List files in the directory
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - echo "Setting image tag..."
      - IMAGE_TAG=$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')

  build:
    commands:
      - echo "Building Docker image..."
      - cd $CODEBUILD_SRC_DIR
      - docker build --platform linux/amd64 -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Creating imagedefinitions.json for Elastic Beanstalk..."
      - printf '[{"name":"my-app-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
